"use client";
import { useEffect, useState } from "react";
import AdminShell from "../../components/AdminShell";
type Visitor = { id: string; date: string; time: string; page: string; referrer: string; device: string; durationMinutes: number };
export default function VisitorsPage() {
  const [rows, setRows] = useState<Visitor[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/admin/auth"), fetch("/api/analytics")]).then(async ([auth, result]) => { if (!(await auth.json()).authenticated) throw new Error("กรุณาเข้าสู่ระบบ"); const json = await result.json(); if (!json.success) throw new Error("โหลดข้อมูลไม่สำเร็จ"); setRows(json.data.recentVisitors || []); }).catch((e) => setError(e.message)); }, []);
  return <AdminShell active="visitors"><main className="min-h-screen bg-[#f4f0e7] p-5 text-[#20352b] md:p-10"><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a47d2e]">Insights</p><h1 className="mt-2 font-serif text-4xl font-bold">Visitors</h1><p className="mt-2 text-sm text-gray-500">รายการผู้เข้าชมล่าสุด</p></header><section className="overflow-hidden rounded-3xl border border-[#dfe7e1] bg-white shadow-sm">{error ? <p className="p-6 text-red-600">{error}</p> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#f8faf8] text-xs uppercase text-gray-500"><tr><th className="px-5 py-4">เวลา</th><th className="px-5 py-4">หน้า</th><th className="px-5 py-4">แหล่งที่มา</th><th className="px-5 py-4">อุปกรณ์</th><th className="px-5 py-4">เวลาใช้งาน</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-[#edf1ee] hover:bg-[#f8faf8]"><td className="px-5 py-4">{row.date} {row.time}</td><td className="px-5 py-4">{row.page}</td><td className="px-5 py-4">{row.referrer || "Direct"}</td><td className="px-5 py-4">{row.device}</td><td className="px-5 py-4">{row.durationMinutes} นาที</td></tr>)}{rows.length === 0 && <tr><td colSpan={5} className="px-5 py-14 text-center text-gray-500">ยังไม่มีข้อมูลผู้เข้าชม</td></tr>}</tbody></table></div>}</section></main></AdminShell>;
}
